name: Pipeline

on:
  pull_request:
    branches: ["*"]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Intall dependencies
        run: yarn install
      - name: Run tests
        run: yarn test

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Intall dependencies
        run: yarn install
      - name: Build Next.js App
        run: yarn build
      - name: Copy Build to EC2
        uses: appleboy/scp-action@v0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ".next/"
          target: "/home/ubuntu"
