name: Pipeline

on:
  pull_request:
    branches: ["*"]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Intall dependencies
        run: yarn install
      - name: Run tests
        run: yarn test

  build:
    runs-on: ubuntu-latest

    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Intall dependencies
        run: yarn install
      - name: Build Next.js App
        run: yarn build
