name: Pipeline

on:
  pull_request:
    branches: ["*"]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Intall dependencies
        run: yarn install
      - name: Run tests
        run: yarn test

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Intall dependencies
        run: yarn install
      - name: Build Next.js App
        run: yarn build
      - name: Debug - List Files in Build Directory
        run: ls -al .next/
      - name: Copy Build to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ./
          target: /home/ubuntu/portfolio_2023/
          rm: true
          overwrite: true

      - name: SSH into EC2 and restart app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt update
            sudo apt install -y nginx

            # Install nvm
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

            # Install the latest version of Node.js
            nvm install node

            # Use the installed Node.js version
            nvm use node

            # Install pm2 globally
            npm install -g pm2

            # Stop and start your application using pm2
            pm2 stop portfolio_2023
            pm2 start yarn --name "portfolio_2023" --interpreter bash -- start
