name: PullRequestsPipeline

on:
  pull_request:
    branches: [master]

jobs:
  Tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Intall dependencies
        run: "yarn install"
      - name: Run tests
        run: yarn test
