name: TestsPipeline

on:
  pull_request:
    branches: ["*"]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Intall dependencies
        run: yarn install
      - name: Run tests
        run: yarn test
